on:
  release:
    types: [created]

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --no-sign
          docker-image: debian:bookworm-slim
      - uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./debian/artifacts/*.deb"]'
